"""Merge the per-photolysis-frequency SAPHIR files of one day into ONE CSV in the
submission format (YYYY-MM-DD.JVALUES.FZJ.csv).

On Z: every j and location is its own file, e.g. 2026-07-03.SAPHIR.SR.jNO2.nc
(inside the chamber) and 2026-07-03.AMBIENT.SR.jNO2.nc (outside), 40 per day.
Values are written unchanged (8 significant digits, more than the instrument
resolves); only the layout changes. Timestamps stay as the data system writes
them (centre of the interval), which the metadata declares.

A hash of the source files (name, size, time) is stored in the CSV header, so
the file is rebuilt only when a source on Z: changed.
"""
from __future__ import annotations

import datetime as dt
import hashlib
import re
from pathlib import Path

import netCDF4
import numpy as np
import pandas as pd

import settings as S

SIG_PREFIX = "# sources_signature = "


def ascii_unit(u: str) -> str:
    """IDL/LaTeX unit markup to plain ASCII: 's!U-1!N' or 's^{-1}' -> 's-1'."""
    u = re.sub(r"!(U|D|N|E|I)", "", str(u), flags=re.IGNORECASE)
    return u.replace("^{", "").replace("}", "").replace("^", "").strip()


def signature(files: list[Path]) -> str:
    h = hashlib.sha1()
    for f in sorted(files, key=lambda p: p.name):
        st = f.stat()
        h.update(f"{f.name}|{st.st_size}|{int(st.st_mtime)}\n".encode())
    return h.hexdigest()[:16]


def existing_signature(csv: Path) -> str | None:
    if not csv.exists():
        return None
    with open(csv, encoding="utf-8") as fh:
        for line in fh:
            if not line.startswith("#"):
                return None
            if line.startswith(SIG_PREFIX):
                return line[len(SIG_PREFIX):].strip()
    return None


def _column(f: Path, day: dt.date) -> tuple[str, pd.Series, dict]:
    name = f.name[len(str(day)) + 1:-3]                    # SAPHIR.SR.jNO2
    loc, _, j = name.split(".", 2)
    with netCDF4.Dataset(f) as nc:
        tv = nc["time"]
        t = netCDF4.num2date(tv[:], tv.units, only_use_python_datetimes=True,
                             only_use_cftime_datetimes=False)
        var = next(k for k in nc.variables if k.startswith("j") and "@" not in k)
        v = nc[var]
        vals = np.ma.filled(v[:].astype(float), np.nan)
        info = {"unit": ascii_unit(getattr(v, "units", "")) or "s-1",
                "pi": getattr(nc, "pi_name", ""), "email": getattr(nc, "email", ""),
                "interval": float(np.nanmedian(np.ma.filled(
                    nc["time@INTERVAL_T"][:].astype(float), np.nan)))
                if "time@INTERVAL_T" in nc.variables else None}
    s = pd.Series(vals, index=pd.DatetimeIndex(pd.to_datetime(list(t))), name=f"{j}_{loc}")
    s = s[~s.index.duplicated()]
    return f"{j}_{loc} [{info['unit']}]", s, info


def build(day: dt.date, files: list[Path]) -> tuple[pd.DataFrame, dict]:
    cols, infos = {}, []
    # chamber (SAPHIR) columns first, then ambient, each alphabetical
    for f in sorted(files, key=lambda p: (not p.name[11:].startswith("SAPHIR"), p.name.lower())):
        col, s, info = _column(f, day)
        cols[col] = s
        infos.append(info)
    df = pd.concat(cols, axis=1).sort_index()
    df = df[df.index.date == day]
    meta = {
        "pi": next((i["pi"] for i in infos if i["pi"]), ""),
        "email": next((i["email"] for i in infos if i["email"]), ""),
        "interval": next((i["interval"] for i in infos if i["interval"]), None),
        "n_sources": len(files),
    }
    return df, meta


def write(day: dt.date, files: list[Path], out_dir: Path) -> Path:
    df, meta = build(day, files)
    tok, inst = S.JVALUES_TOKEN
    out = out_dir / f"{day}.{tok}.{inst}.csv"
    t = df.index
    fmt = "%Y-%m-%d %H:%M:%S.%f" if (t.microsecond != 0).any() else "%Y-%m-%d %H:%M:%S"
    body = df.copy()
    body.insert(0, "time_utc", t.strftime(fmt))
    header = [
        f"# SAPHFIRE 2026 photolysis frequencies, {day} (UTC)",
        f"# Merged unchanged from {meta['n_sources']} SAPHIR spectroradiometer files on "
        f"{S.SAPHIR_Z} (SAPHIR = inside the chamber, AMBIENT = outside)",
        "# time_utc = centre of the averaging interval, as written by the SAPHIR data system",
        f"{SIG_PREFIX}{signature(files)}",
    ]
    tmp = out.with_name(f"~{out.name}.tmp")
    with open(tmp, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(header) + "\n")
        body.to_csv(fh, index=False, float_format="%.8g", na_rep="", lineterminator="\n")
    tmp.replace(out)
    _write_metadata(out_dir, meta)
    return out


def _write_metadata(out_dir: Path, meta: dict) -> None:
    tok, inst = S.JVALUES_TOKEN
    path = out_dir / f"Metadata.{tok}.{inst}.txt"
    pi, email = meta["pi"], meta["email"]          # read from the SAPHIR files
    text = "\n".join([
        f"# Metadata.{tok}.{inst}.txt (generated by import_saphir.py from the SAPHIR files)",
        f"instrument = {tok}",
        f"institution = {inst}",
        "data_format = csv",
        "instrument_long = Spectroradiometers, chamber (SAPHIR) and ambient",
        "measured_quantities = photolysis frequencies at 298 K",
        f"pi_name = {pi}",
        f"pi_email = {email}",
        "institute = ICE-3 Troposphere",
        f"coauthors = {pi} <{email}>",
        f"integration_time_s = {meta['interval']:g}" if meta["interval"] else "",
        "time_reference = centre",
        "comments = Values copied unchanged from the native SAPHIR NetCDF files on Z:.",
        "comments = Column suffix _SAPHIR = inside the chamber, _AMBIENT = outside.",
    ]).replace("\n\n", "\n") + "\n"
    if not path.exists() or path.read_text(encoding="utf-8") != text:
        tmp = path.with_name(f"~{path.name}.tmp")
        tmp.write_text(text, encoding="utf-8", newline="\n")
        tmp.replace(path)
